# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r_packages:
  - covr
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
notifications:
  email:
    on_success: change
    on_failure: change

